export { startAttentionPipeline } from './cmf/attention';
export type { BucketAggregate, PipelineCallbacks, PipelineHandle } from './cmf/attention';
export { average, BUCKET_MS, Bucketer, bucketStartFor } from './cmf/bucketing';
export { Calibration, CALIBRATION_STAGES } from './cmf/calibration';
export type { CalibrationResult, CalibrationStage } from './cmf/calibration';
export { headState } from './cmf/headTolerance';
export type { HeadState } from './cmf/headTolerance';
export { engagementScore } from './cmf/score';
export type { AttentionSignals, Baseline } from './cmf/score';
export * as ubp from './ubp';
export { AttentionChart } from './ui/AttentionChart';
export { PrivacyIndicator } from './ui/PrivacyIndicator';
