# Generated by Django 5.1.15 on 2026-08-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0003_alter_homework_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="max_score",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
