# Generated by Django 5.1.15 on 2026-08-13 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homework", "0003_alter_homework_deleted_at"),
        ("scheduling", "0005_projectorcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "DRAFT"), ("sent", "SENT")],
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("intro", models.TextField(blank=True, default="")),
                ("assembled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("speech_omitted", models.BooleanField(default=False)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="summaries_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="scheduling.lessonsession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lesson summaries",
            },
        ),
        migrations.CreateModel(
            name="SummaryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("topic", "TOPIC"),
                            ("words", "WORDS"),
                            ("watch", "WATCH"),
                            ("chat", "CHAT"),
                            ("homework", "HOMEWORK"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("plan", "PLAN"),
                            ("board", "BOARD"),
                            ("speech", "SPEECH"),
                            ("material", "MATERIAL"),
                            ("test", "TEST"),
                            ("chat", "CHAT"),
                            ("teacher", "TEACHER"),
                        ],
                        max_length=12,
                    ),
                ),
                ("source_meta", models.JSONField(blank=True, default=dict)),
                ("at_offset_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("text", models.TextField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("edited", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="summary_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="summary_items",
                        to="homework.homework",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="summaries.lessonsummary",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["summary", "section"], name="summaries_s_summary_f95358_idx"
                    )
                ],
            },
        ),
    ]
