# Generated by Django 5.1.4 on 2026-08-31 11:44

import people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=people.models.new_id,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "role",
                    models.CharField(
                        choices=[("teacher", "веду уроки"), ("student", "учусь")],
                        default="student",
                        max_length=16,
                    ),
                ),
                ("pass_hash", models.CharField(max_length=256)),
                ("made_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "people",
            },
        ),
    ]
