# Generated by Django 5.1.4 on 2026-08-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tries",
            fields=[
                (
                    "key",
                    models.CharField(max_length=254, primary_key=True, serialize=False),
                ),
                ("fails", models.PositiveIntegerField(default=0)),
                ("until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tries",
            },
        ),
        migrations.CreateModel(
            name="Reset",
            fields=[
                (
                    "token_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resets",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "resets",
            },
        ),
    ]
