# Generated by Django 5.1.15 on 2026-08-13 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_user_active_learning_profile"),
        ("courses", "0007_course_grading_scale"),
        ("homework", "0003_alter_homework_deleted_at"),
        ("scheduling", "0005_projectorcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("live", "LIVE"),
                            ("homework", "HOMEWORK"),
                            ("practice", "PRACTICE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "homework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercise_sets",
                        to="homework.homework",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_sets",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vocab_card", "VOCAB_CARD"),
                            ("cloze", "CLOZE"),
                            ("choice", "CHOICE"),
                            ("word_order", "WORD_ORDER"),
                            ("match", "MATCH"),
                            ("listening", "LISTENING"),
                            ("dictation", "DICTATION"),
                            ("pronunciation", "PRONUNCIATION"),
                            ("speaking", "SPEAKING"),
                            ("writing", "WRITING"),
                            ("transform", "TRANSFORM"),
                            ("roleplay", "ROLEPLAY"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("vocab", "VOCAB"),
                            ("grammar", "GRAMMAR"),
                            ("listening", "LISTENING"),
                            ("reading", "READING"),
                            ("writing", "WRITING"),
                            ("speaking", "SPEAKING"),
                            ("pronunciation", "PRONUNCIATION"),
                        ],
                        max_length=14,
                    ),
                ),
                ("cefr_level", models.CharField(blank=True, default="", max_length=4)),
                ("skill_tags", models.JSONField(blank=True, default=list)),
                ("prompt", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("answer_key", models.JSONField(blank=True, default=dict)),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="courses.material",
                    ),
                ),
                (
                    "exercise_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="exercises.exerciseset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("live", "LIVE"),
                            ("homework", "HOMEWORK"),
                            ("practice", "PRACTICE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("response", models.JSONField(blank=True, default=dict)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("score", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("hints_used", models.PositiveIntegerField(default=0)),
                (
                    "lesson_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercise_attempts",
                        to="scheduling.lessonsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_attempts",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exercises.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["exercise", "created_at"], name="exercises_a_exercis_56fa6f_idx"
                    ),
                    models.Index(
                        fields=["student", "context"], name="exercises_a_student_582311_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillMastery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skill_tag", models.CharField(max_length=120)),
                ("p_known", models.FloatField(default=0.25)),
                ("opportunities", models.PositiveIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_mastery",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "skill_tag"], name="exercises_s_student_06cbc9_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "skill_tag"), name="uniq_skill_mastery"
                    )
                ],
            },
        ),
    ]
