# Generated by Django 5.1.15 on 2026-08-13 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_consent_speech_user_consent_speech_at"),
        ("courses", "0009_material_attribution_material_license_and_more"),
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LexicalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lemma", models.CharField(max_length=120)),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("noun", "NOUN"),
                            ("verb", "VERB"),
                            ("adjective", "ADJECTIVE"),
                            ("adverb", "ADVERB"),
                            ("phrase", "PHRASE"),
                            ("other", "OTHER"),
                        ],
                        max_length=12,
                    ),
                ),
                ("sense_id", models.CharField(blank=True, default="", max_length=64)),
                ("cefr_level", models.CharField(blank=True, default="", max_length=4)),
                ("ipa", models.CharField(blank=True, default="", max_length=120)),
                ("definition_ru", models.TextField(blank=True, default="")),
                ("translation_ru", models.CharField(blank=True, default="", max_length=300)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("wordnet", "WORDNET"),
                            ("tatoeba", "TATOEBA"),
                            ("common_voice", "COMMON_VOICE"),
                            ("own", "OWN"),
                        ],
                        max_length=16,
                    ),
                ),
                ("license", models.CharField(max_length=64)),
                ("attribution", models.CharField(max_length=300)),
                ("source_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "illustration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="illustrated_words",
                        to="courses.material",
                    ),
                ),
                (
                    "lessons",
                    models.ManyToManyField(blank=True, related_name="words", to="courses.lesson"),
                ),
                (
                    "pronunciation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pronounced_words",
                        to="courses.material",
                    ),
                ),
            ],
            options={
                "ordering": ["lemma", "sense_id"],
            },
        ),
        migrations.CreateModel(
            name="LexicalExample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("translation_ru", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("wordnet", "WORDNET"),
                            ("tatoeba", "TATOEBA"),
                            ("common_voice", "COMMON_VOICE"),
                            ("own", "OWN"),
                        ],
                        max_length=16,
                    ),
                ),
                ("license", models.CharField(max_length=64)),
                ("attribution", models.CharField(max_length=300)),
                ("source_url", models.URLField(blank=True, default="", max_length=1000)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="exercises.lexicalitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SrsCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("recognition", "RECOGNITION"), ("recall", "RECALL")],
                        default="recognition",
                        max_length=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("learning", "LEARNING"),
                            ("review", "REVIEW"),
                            ("relearning", "RELEARNING"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("stability", models.FloatField(default=0.0)),
                ("difficulty", models.FloatField(default=0.0)),
                ("due_at", models.DateTimeField()),
                ("last_review_at", models.DateTimeField(blank=True, null=True)),
                ("reps", models.PositiveIntegerField(default=0)),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("params_version", models.CharField(default="fsrs-v1", max_length=16)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="exercises.lexicalitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_cards",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lexicalitem",
            index=models.Index(fields=["lemma"], name="exercises_l_lemma_3ab9db_idx"),
        ),
        migrations.AddConstraint(
            model_name="lexicalitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sense_id__gt", "")),
                fields=("source", "sense_id"),
                name="uniq_lexical_sense",
            ),
        ),
        migrations.AddConstraint(
            model_name="lexicalitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("license", ""), _negated=True),
                    models.Q(("attribution", ""), _negated=True),
                ),
                name="lexical_item_is_attributed",
            ),
        ),
        migrations.AddConstraint(
            model_name="lexicalexample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("license", ""), _negated=True),
                    models.Q(("attribution", ""), _negated=True),
                ),
                name="lexical_example_is_attributed",
            ),
        ),
        migrations.AddIndex(
            model_name="srscard",
            index=models.Index(fields=["student", "due_at"], name="exercises_s_student_7de394_idx"),
        ),
        migrations.AddConstraint(
            model_name="srscard",
            constraint=models.UniqueConstraint(
                fields=("student", "item", "direction"), name="uniq_srs_card"
            ),
        ),
    ]
