# Generated by Django 5.1.15 on 2026-08-13 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_consent_speech_user_consent_speech_at"),
        ("exercises", "0002_lexicalitem_lexicalexample_srscard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="srscard",
            name="learning_steps",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="StudyStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_days", models.PositiveIntegerField(default=0)),
                ("longest_days", models.PositiveIntegerField(default=0)),
                ("last_day", models.DateField(blank=True, null=True)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EarnedAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("first_word", "FIRST_WORD"),
                            ("ten_words", "TEN_WORDS"),
                            ("fifty_words", "FIFTY_WORDS"),
                            ("first_mastered", "FIRST_MASTERED"),
                            ("ten_mastered", "TEN_MASTERED"),
                            ("streak_3", "STREAK_3"),
                            ("streak_7", "STREAK_7"),
                            ("streak_30", "STREAK_30"),
                            ("hundred_reviews", "HUNDRED_REVIEWS"),
                        ],
                        max_length=24,
                    ),
                ),
                ("earned_at", models.DateTimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["earned_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "earned_at"], name="exercises_e_student_09aab1_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "key"), name="uniq_earned_achievement"
                    )
                ],
            },
        ),
    ]
