# Generated by Django 5.2.17 on 2026-10-06 10:14

import django.db.models.deletion
import science.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=science.models.new_code,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("consent", models.CharField(blank=True, max_length=20)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "science_volunteers",
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=science.models.new_id,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("protocol", models.CharField(max_length=24)),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("device", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("bytes", models.BigIntegerField(default=0)),
                ("chunks", models.IntegerField(default=0)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="science.volunteer",
                    ),
                ),
            ],
            options={
                "db_table": "science_runs",
                "ordering": ["started"],
            },
        ),
    ]
