# Generated by Django 5.2.17 on 2026-10-06 15:26

import django.db.models.deletion
import science.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "token",
                    models.CharField(
                        default=science.models.new_token,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "science_invites",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="volunteer",
            name="name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="invite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteers",
                to="science.invite",
            ),
        ),
    ]
