# Generated by Django 5.1.15 on 2026-08-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_revokedtoken_user_token_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jurisdiction",
            field=models.CharField(
                blank=True,
                choices=[("ru", "RU"), ("eu", "EU"), ("unknown", "UNKNOWN")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jurisdiction_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contract", "CONTRACT"),
                    ("kyc_verified", "KYC_VERIFIED"),
                    ("deployment", "DEPLOYMENT"),
                    ("self_declared", "SELF_DECLARED"),
                    ("inferred", "INFERRED"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jurisdiction_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
