# Generated by Django 5.1.15 on 2026-08-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_jurisdiction_user_jurisdiction_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_learning_profile",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
