# Generated by Django 5.1.15 on 2026-08-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_active_learning_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consent_speech",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_speech_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
