# Generated by Django 5.1.15 on 2026-08-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_consent_speech_user_consent_speech_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consent_attention",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_attention_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
