# Generated by Django 5.1.15 on 2026-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_consent_attention_user_consent_attention_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consent_152fz",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_152fz_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
