# Generated by Django 5.1.15 on 2026-08-15 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_consent_152fz_user_consent_152fz_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationdocument",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="filename",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifications_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(
                fields=["status", "created_at"], name="accounts_ve_status_200a4f_idx"
            ),
        ),
    ]
