# Generated by Django 5.1.15 on 2026-08-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_verificationdocument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
