# Generated by Django 5.1.15 on 2026-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consent_attention_device_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_speech_device_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
