# Generated by Django 5.1.15 on 2026-08-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_consent_attention_device_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
