# Generated by Django 5.1.15 on 2026-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="connection_type",
            field=models.CharField(
                choices=[("direct", "DIRECT"), ("relay", "RELAY"), ("unknown", "UNKNOWN")],
                default="unknown",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="uplink_mbps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="uplink_measured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
