# Generated by Django 5.1.15 on 2026-08-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_device_connection_type_device_uplink_mbps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="backup_configured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="backup_kind",
            field=models.CharField(
                choices=[
                    ("none", "NONE"),
                    ("external_disk", "EXTERNAL_DISK"),
                    ("cloud_folder", "CLOUD_FOLDER"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="cloud_copy_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="last_backup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="setup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="setup_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
