# Generated by Django 5.1.15 on 2026-08-14 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0003_institution_jurisdiction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(db_index=True, max_length=32, unique=True)),
                ("code", models.CharField(db_index=True, max_length=12, unique=True)),
                (
                    "access_mode",
                    models.CharField(
                        choices=[
                            ("group_only", "GROUP_ONLY"),
                            ("any_authenticated", "ANY_AUTHENTICATED"),
                            ("knock", "KNOCK"),
                        ],
                        default="group_only",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_point",
                        to="institutions.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RetiredLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(db_index=True, max_length=32, unique=True)),
                ("code", models.CharField(max_length=12)),
                ("retired_at", models.DateTimeField()),
                (
                    "meeting_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retired_links",
                        to="meetingpoint.meetingpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-retired_at"],
            },
        ),
    ]
