# Generated by Django 5.1.15 on 2026-08-14 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_consent_speech_user_consent_speech_at"),
        ("meetingpoint", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MirroredRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("work", "WORK"),
                            ("summary", "SUMMARY"),
                            ("achievement", "ACHIEVEMENT"),
                            ("chat", "CHAT"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mirrored_records",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "kind", "-occurred_at"],
                        name="meetingpoin_student_32117c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "kind", "source_id"), name="uniq_mirrored_record"
                    )
                ],
            },
        ),
    ]
