# Generated by Django 5.1.15 on 2026-08-14 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_consent_attention_user_consent_attention_at"),
        ("meetingpoint", "0002_mirroredrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mirroredrecord",
            name="kind",
            field=models.CharField(
                choices=[
                    ("work", "WORK"),
                    ("summary", "SUMMARY"),
                    ("achievement", "ACHIEVEMENT"),
                    ("chat", "CHAT"),
                    ("diary", "DIARY"),
                    ("board", "BOARD"),
                    ("material", "MATERIAL"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="MeetingVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_opened_at", models.DateTimeField()),
                (
                    "meeting_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="meetingpoint.meetingpoint",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_visits",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["meeting_point", "last_opened_at"],
                        name="meetingpoin_meeting_06ed41_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting_point", "student"), name="uniq_meeting_visit"
                    )
                ],
            },
        ),
    ]
