# Generated by Django 5.1.15 on 2026-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="access_status",
            field=models.CharField(
                choices=[("active", "ACTIVE"), ("pending_payment", "PENDING_PAYMENT")],
                default="active",
                max_length=16,
            ),
        ),
    ]
