# Generated by Django 5.1.15 on 2026-06-15 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_currency_course_price_and_more"),
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="institutions.group",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="institutions.institution",
            ),
        ),
    ]
