# Generated by Django 5.1.15 on 2026-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0003_course_group_course_institution"),
        ("institutions", "0002_alter_institution_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="courses_cou_status_158bbf_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "access_status"], name="courses_enr_student_10772b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["status"], name="courses_les_status_0b084d_idx"),
        ),
    ]
