# Generated by Django 5.1.15 on 2026-08-12 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_deleted_at_alter_lesson_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="device_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="lesson",
            name="kind",
            field=models.CharField(
                choices=[("standard", "STANDARD"), ("external_device", "EXTERNAL_DEVICE")],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SavedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("url", models.URLField(blank=True, default="", max_length=1000)),
                ("source_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("saved", "SAVED"), ("watch_later", "WATCH_LATER")],
                        default="saved",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_items",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_items",
                        to="courses.lesson",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="courses.material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "course"], name="courses_sav_user_id_91ad6a_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("material__isnull", False)),
                        fields=("user", "material"),
                        name="uniq_saved_material_per_user",
                    )
                ],
            },
        ),
    ]
