# Generated by Django 5.1.15 on 2026-08-13 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
        ("courses", "0005_lesson_device_key_lesson_kind_saveditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="board_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="board.boardsnapshot",
            ),
        ),
    ]
