# Generated by Django 5.1.15 on 2026-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_material_board_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="grading_scale",
            field=models.CharField(
                blank=True,
                choices=[("five_point", "FIVE_POINT"), ("percent", "PERCENT")],
                default="",
                max_length=12,
            ),
        ),
    ]
