# Generated by Django 5.1.15 on 2026-08-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_grading_scale"),
        ("summaries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="summaries.lessonsummary",
            ),
        ),
    ]
