# Generated by Django 5.1.15 on 2026-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_material_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="attribution",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="material",
            name="license",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="material",
            name="source_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
