# Generated by Django 5.1.15 on 2026-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_material_attribution_material_license_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="shared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
