# Generated by Django 5.1.15 on 2026-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_material_shared_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="format",
            field=models.CharField(
                choices=[
                    ("program", "PROGRAM"),
                    ("course", "COURSE"),
                    ("professional", "PROFESSIONAL"),
                ],
                default="program",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("preschool", "PRESCHOOL"),
                    ("grade_1", "GRADE_1"),
                    ("grade_2", "GRADE_2"),
                    ("grade_3", "GRADE_3"),
                    ("grade_4", "GRADE_4"),
                    ("grade_5", "GRADE_5"),
                    ("grade_6", "GRADE_6"),
                    ("grade_7", "GRADE_7"),
                    ("grade_8", "GRADE_8"),
                    ("grade_9", "GRADE_9"),
                    ("grade_10", "GRADE_10"),
                    ("grade_11", "GRADE_11"),
                    ("college", "COLLEGE"),
                    ("university", "UNIVERSITY"),
                    ("adult", "ADULT"),
                ],
                max_length=12,
            ),
        ),
    ]
