# Generated by Django 5.1.15 on 2026-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_courseinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "ACTIVE"),
                    ("completed", "COMPLETED"),
                    ("pending_teacher", "PENDING_TEACHER"),
                    ("pending_consent", "PENDING_CONSENT"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
