# Generated by Django 5.1.15 on 2026-08-13 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0005_lesson_device_key_lesson_kind_saveditem"),
        ("institutions", "0003_institution_jurisdiction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subject_group", "SUBJECT_GROUP"),
                            ("pupil_teacher", "PUPIL_TEACHER"),
                            ("peer", "PEER"),
                            ("staff_room", "STAFF_ROOM"),
                        ],
                        max_length=16,
                    ),
                ),
                ("pair_key", models.CharField(blank=True, default="", max_length=128)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_channels",
                        to="courses.course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_channels",
                        to="institutions.group",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_channels",
                        to="institutions.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatchannel",
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.chatchannel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "OPEN"),
                            ("reviewed", "REVIEWED"),
                            ("dismissed", "DISMISSED"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="chat.chatchannel",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="chat.channelmessage",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionChatSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("teacher_visible_always", models.BooleanField(default=False)),
                ("premoderation", models.BooleanField(default=False)),
                ("direct_messages_enabled", models.BooleanField(default=True)),
                ("stopwords", models.JSONField(blank=True, default=list)),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_settings",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="chatchannel",
            index=models.Index(
                fields=["kind", "last_message_at"], name="chat_chatch_kind_746a5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pair_key__gt", "")),
                fields=("pair_key",),
                name="uniq_direct_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "subject_group")),
                fields=("course", "group"),
                name="uniq_subject_group_channel",
            ),
        ),
        migrations.AddIndex(
            model_name="channelmessage",
            index=models.Index(
                fields=["channel", "sent_at"], name="chat_channe_channel_7bd02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(fields=["user", "channel"], name="chat_channe_user_id_a14648_idx"),
        ),
        migrations.AddConstraint(
            model_name="channelmembership",
            constraint=models.UniqueConstraint(
                fields=("channel", "user"), name="uniq_channel_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="chatreport",
            index=models.Index(fields=["channel", "status"], name="chat_chatre_channel_f8f672_idx"),
        ),
    ]
