# Generated by Django 5.2.17 on 2026-09-01 10:59

import django.db.models.deletion
import study.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "token_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="came_by",
                        to="people.person",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "invites",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=study.models.new_id,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("on", models.DateField()),
                ("at", models.TimeField()),
                ("minutes", models.PositiveIntegerField(default=45)),
                (
                    "code",
                    models.CharField(
                        default=study.models.new_code, max_length=14, unique=True
                    ),
                ),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["on", "at"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=study.models.new_id,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("doc", "документ"),
                            ("image", "картинка"),
                            ("link", "ссылка"),
                        ],
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("path", models.CharField(blank=True, default="", max_length=300)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="study.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "materials",
                "ordering": ["made_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=study.models.new_id,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="study.lesson",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "visits",
            },
        ),
        migrations.CreateModel(
            name="Bond",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=study.models.new_id,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("how", models.CharField(default="ссылке", max_length=16)),
                ("since", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="people.person",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "bonds",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher", "student"), name="одна_связь_на_пару"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["teacher", "on"], name="lessons_teacher_d71b0f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.UniqueConstraint(
                fields=("lesson", "person"), name="одно_посещение_на_урок"
            ),
        ),
    ]
