# Generated by Django 5.2.17 on 2026-09-02 22:07

import django.db.models.deletion
import study.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_tries_reset"),
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=study.models.new_id,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("text", "сообщение"), ("invite", "зову на занятие")],
                        default="text",
                        max_length=8,
                    ),
                ),
                ("text", models.CharField(blank=True, default="", max_length=2000)),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="study.lesson",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received",
                        to="people.person",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["made_at"],
                "indexes": [
                    models.Index(
                        fields=["receiver", "sender", "made_at"],
                        name="messages_receive_5c2c45_idx",
                    ),
                    models.Index(
                        fields=["receiver", "read_at"],
                        name="messages_receive_d8f769_idx",
                    ),
                ],
            },
        ),
    ]
