# Generated by Django 5.1.15 on 2026-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_deleted_at_alter_lesson_deleted_at_and_more"),
        ("institutions", "0002_alter_institution_deleted_at"),
        ("scheduling", "0002_lessonsession_group"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lessonsession",
            index=models.Index(fields=["start_at"], name="scheduling__start_a_e47df9_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonsession",
            index=models.Index(fields=["status"], name="scheduling__status_518343_idx"),
        ),
    ]
