# Generated by Django 5.1.15 on 2026-08-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_lessonsession_scheduling__start_a_e47df9_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonsession",
            name="recording_key",
        ),
    ]
