# Generated by Django 5.1.15 on 2026-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_projectorcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsession",
            name="closed_automatically",
            field=models.BooleanField(default=False),
        ),
    ]
