# Generated by Django 5.1.15 on 2026-08-11 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_version", models.CharField(max_length=32)),
                ("matrix_sha256", models.CharField(max_length=64)),
                ("observed_by", models.CharField(default="runtime", max_length=32)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_version", "matrix_sha256"), name="uniq_policy_version_hash"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyDecisionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_kind", models.CharField(max_length=16)),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                ("feature", models.CharField(max_length=64)),
                ("allowed", models.BooleanField(default=False)),
                ("reason", models.CharField(max_length=64)),
                ("jurisdiction", models.CharField(max_length=16)),
                ("jurisdiction_source", models.CharField(max_length=16)),
                ("policy_version", models.CharField(max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "feature", "created_at"],
                        name="compliance__tenant__cf4d88_idx",
                    ),
                    models.Index(fields=["created_at"], name="compliance__created_9fb9ba_idx"),
                ],
            },
        ),
    ]
