# Generated by Django 5.1.15 on 2026-08-15 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("viewed_document", "открыл документ"),
                            ("viewed_queue", "открыл очередь верификации"),
                            ("verified", "верифицировал преподавателя"),
                            ("rejected", "отказал в верификации"),
                            ("requested_documents", "запросил документы"),
                        ],
                        max_length=32,
                    ),
                ),
                ("object_label", models.CharField(blank=True, default="", max_length=200)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oversight_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oversight_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="oversight_a_created_2e2be2_idx"),
                    models.Index(
                        fields=["subject_user", "-created_at"],
                        name="oversight_a_subject_2a7860_idx",
                    ),
                ],
            },
        ),
    ]
