# Generated by Django 5.1.15 on 2026-08-15 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oversight", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("viewed_document", "открыл документ"),
                    ("viewed_queue", "открыл очередь верификации"),
                    ("verified", "верифицировал преподавателя"),
                    ("state_changed", "изменил состояние учётной записи"),
                    ("rejected", "отказал в верификации"),
                    ("requested_documents", "запросил документы"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AccountStateRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "активен"),
                            ("limited", "ограничен"),
                            ("blocked", "заблокирован"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="state_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="oversight_a_user_id_111c3f_idx"
                    )
                ],
            },
        ),
    ]
